name: Naver Blog Search

on:
  push:
    paths:
      - crawl_trigger.json

jobs:
  search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run search
        run: python crawl.py

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add results.json
          git commit -m "🔍 Search results updated"
          git push
